exceptions:
    resource: "@ExceptionsBundle/Controller/"
    type:     annotation
    prefix:   /

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /manager/_trans

cmsSecurity:
    resource: "@CMSBundle/Controller/SecurityController.php"
    type:     annotation
    prefix:   /

cmsAdmin:
    resource: "@CMSBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /

cmsBanner:
    resource: "@CMSBundle/Controller/BannerController.php"
    type:     annotation
    prefix:   /

cmsBlock:
    resource: "@CMSBundle/Controller/BlockController.php"
    type:     annotation
    prefix:   /

cmsDefault:
    resource: "@CMSBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

cmsFAQ:
    resource: "@CMSBundle/Controller/FAQController.php"
    type:     annotation
    prefix:   /

cmsPage:
    resource: "@CMSBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /

cmsPost:
    resource: "@CMSBundle/Controller/PostController.php"
    type:     annotation
    prefix:   /

cmsReview:
    resource: "@CMSBundle/Controller/ReviewController.php"
    type:     annotation
    prefix:   /

cmsSlide:
    resource: "@CMSBundle/Controller/SlideController.php"
    type:     annotation
    prefix:   /

extendcms:
    resource: "@ExtendCMSBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

post_show:
    path:      /новости/{url}
    defaults:  { _controller: CMSBundle:Default:showPost }

page_show:
    path:      /{url}
    defaults:  { _controller: CMSBundle:Default:showPage }
    requirements:
        url: .+
